const express = require('express')
const serveStatic = require('serve-static')
const path = require('path')
const app = express()
app.use('/', serveStatic(path.join(__dirname, '/dist')))
app.use('/bong-da', serveStatic(path.join(__dirname, '/dist')))
app.use('/chi-tiet-bai-viet', serveStatic(path.join(__dirname, '/dist')))
app.use('/bong-da/giai-ngoai-hang-anh', serveStatic(path.join(__dirname, '/dist')))
app.use('/bong-da/champions-league', serveStatic(path.join(__dirname, '/dist')))
app.use('/bong-da/la-liga', serveStatic(path.join(__dirname, '/dist')))
app.use('/bong-da/bundesliga', serveStatic(path.join(__dirname, '/dist')))
app.use('/bong-da/serie-a', serveStatic(path.join(__dirname, '/dist')))
const port = process.env.PORT || 8080
app.listen(port)